exports.up = function(knex) {
   return knex.schema.createTable('cq_inst_gpon', function (table) {
        table.increments('id').primary();
        table.string('cluster', 30);
        table.string('sup',50);
        table.string('atividade',40);
        table.string('telefone',15);
        table.string('ard',15);
        table.string('tecnico',60);
        table.string('documento',25);
        table.string('documento2',25);
        table.string('prod',40);
        table.datetime('envio');
        table.datetime('vencimento');
        table.string('cadastrado',15);
        table.datetime('vistoria');
        table.datetime('encerramento');
        table.string('total_rep', 3);
        table.string('cq', 3);
        table.string('rede', 15);
        table.string('supervisor', 60);
        table.string('matsupervisor', 10);
        table.string('cloud', 6);
        table.string('recente', 3);
        table.string('empresa', 13);
        table.string('statuscode', 6);
        table.string('endereco', 90);
        table.string('cliente', 60);
        table.string('projeto', 30);
        table.string('acabamento_rede_interna', 40);
        table.string('avalicao_tecnico_pelo_cliente', 20);
        table.string('cliente_orientado', 40);
        table.string('clientes_conector_autofusao', 20);
        table.string('clientes_configurados', 60);
        table.string('configurado_canais', 60);
        table.string('cto_dgoi_cdoi_cdoe_caixa_tar', 30);
        table.string('drop_feb',  30);
        table.string('equipagem_postes', 60);
        table.string('equipamento_rede_cliente', 60);
        table.string('estrutura', 60);
        table.string('etiqueta_identificacao', 60);
        table.string('extencao_linha', 60);
        table.string('facilidades_atualiadas', 60);
        table.string('jumper_padrao', 60);
        table.string('modem_melhor_local', 60);
        table.string('observacao', 60);
        table.string('orientacao_movimentacao_fibra', 60);
        table.string('pacote', 10);
        table.string('parametros_modem', 60);
        table.string('pingadeira_reserva_tecnica', 60);
        table.string('postura_tecnico', 60);
        table.string('questionamento_tecnico_n_soube', 60);
        table.string('satisfacao_produto', 60);
        table.string('tecnico_deixou_cliente_acoes', 60);
        table.string('tecnico_foi_cordial', 60);
        table.string('tecnologia', 10);
        table.string('tipo_tv', 10);
        table.string('tomada_padrao', 60);
        table.string('images', 60);
        table.string('latitude', 60);
        table.string('logintude', 60);
        table.timestamps();
    });
};

exports.down = function(knex) {
  return knex.schema.droTable('cq_inst_gpon');
};
